config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  
  resources :footsteps do
    resources :comments, only: [:create]
    member do
      post 'copy'
    end
  end
  
  resources :categories, only: [:create, :new, :show]
  
  resources :users, only: [:create, :show, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
  
  has_many :footstep_categories
  has_many :footsteps, through: :footstep_categories
  
  validates :name, presence: true, uniqueness: true
  
  sluggable_column :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base  
  belongs_to :user
  belongs_to :footstep
  
  validates :body, presence: true
end

app/models/footstep.rb
class Footstep < ActiveRecord::Base
  PER_PAGE = 10
  
  include Sluggable
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :footstep_categories
  has_many :categories, through: :footstep_categories
  
  validates :title, presence: true
  
  sluggable_column :title

end

app/models/footstep_category.rb
class FootstepCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :footstep
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable
  
  has_many :footsteps
  has_many :comments
  
  has_secure_password validations: false
  validates :password, presence: true, on: :create, length: {minimum: 6}
  validates :username, presence: true, uniqueness: true
  
  sluggable_column :username
  
  def admin?
    self.role == 'admin'
  end
  
  def moderator?
    self.role == 'moderator'
  end
  
  def count_completed
    footsteps.where(completed: true).count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    access_denied unless logged_in?
  end
  
  def require_admin
    access_denied unless logged_in? and current_user.admin?
  end
  
  def access_denied
    flash['error'] = "You can't do that."
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]
  
  def show
    @category = Category.find_by slug: params[:id]
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash['notice'] = "Category was successfully created."
      redirect_to root_path
    else
      render :new
    end
  end
  
  private
  def category_params
    params.require(:category).permit!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  
  def create
    @footstep = Footstep.find_by slug: params[:footstep_id]
    @comment = @footstep.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash['notice'] = "Your comment was successfully created."
      redirect_to footstep_path(@footstep)
    else
      render 'footsteps/show'
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit!
  end
end

app/controllers/footsteps_controller.rb
class FootstepsController < ApplicationController
  before_action :set_footstep, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @footsteps = (Footstep.all.where(private: false).limit(Footstep::PER_PAGE).offset(params[:offset])).sort_by{|x| x.created_at}.reverse
    @pages = (Footstep.all.size / Footstep::PER_PAGE) 
    @pages += 1 if (Footstep.all.size % Footstep::PER_PAGE) > 0
  end
  
  def show
    @comment = Comment.new
  end
  
  def new
    @footstep = Footstep.new
  end
  
  def create
    @footstep = Footstep.new(footstep_params)
    @footstep.user = current_user
    if @footstep.save
      flash['notice'] = "Your footstep was successfully created."
      redirect_to user_path(current_user)
    else
      render :new
    end
  end
  
  def update
    if @footstep.update(footstep_params)
      flash['notice'] = "Your footstep was successfully updated."
      redirect_to footstep_path(@footstep)
    else
      render :edit
    end
  end
  
  def edit
  end
  
  def destroy
    if @footstep.destroy
      flash['error'] = "Your footstep was deleted."
      redirect_to user_path(current_user)
    end
  end
  
  def copy
    @existing_footstep = Footstep.find_by(id: params[:id])
    @footstep = Footstep.new(@existing_footstep.attributes)
    @footstep.category_ids = @existing_footstep.category_ids
  end
  
  private
  def footstep_params
    params.require(:footstep).permit!
  end
  
  def set_footstep
    @footstep = Footstep.find_by slug: params[:id]
  end
  
  def require_same_user
    access_denied unless logged_in? and (current_user == @footstep.user || current_user.admin?)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash['notice'] = "You're logged in."
      redirect_to root_path
    else
      flash['error'] = "There is something wrong with your username or password."
      redirect_to login_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash['notice'] = "You're logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]
  
  def show
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash['notice'] = "Your profile was successfully created. You're now logged in."
      redirect_to root_path
    else
      render :new
    end
  end
  
  def update
    if @user.update(user_params)
      flash['notice'] = "Your profile was successfully updated."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  def edit
  end
  
  private
  def user_params
    params.require(:user).permit!
  end
  
  def set_user
    @user = User. find_by slug: params[:id]
  end
  
  def require_same_user
    access_denied unless logged_in? and (current_user == @user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_datetime(date)
    if logged_in? && !current_user.time_zone.blank?
      date = date.in_time_zone(current_user.time_zone)
    end
    date.strftime("%m/%d/%Y %l:%M%P %Z")
  end
end

app/views/categories/_category.html.erb
<span class="label label-info"><%= link_to category.name, category_path(category) %> </span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a New Category' %>

<%= render 'shared/errors', obj: @category %>

<div class='row'>
  <div class='form-group'>
    <%= form_for @category do |f| %>
      <div class='form-group col-sm-4'>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class='col-sm-12'>
        <%= f.submit "Create Category", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>
<hr>
<div>
  <h5>Current categories include:</h5>
  <% Category.all.sort{|a,b| a['name']<=>b['name']}.each do |category| %>
    <%= render 'category', category: category %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Footsteps', footsteps_path) + " &raquo; #{@category.name}".html_safe %>
<%= render 'shared/content_title', title: header %>

<% @category.footsteps.each do |footstep| %>
  <%= render '/footsteps/footstep', footstep: footstep %>
<% end %>

app/views/comments/_comment.html.erb
<% show_footstep ||= false %>

<% if !comment.footstep.private? %>
<div class='well col-sm-8'>
  <p>"<%= comment.body %>"</p>
  <p>
    <span class='quiet'>
      <% if show_footstep %>
        on <%= link_to comment.footstep.title, footstep_path(comment.footstep) %>
        <br/>
      <% end %>
      comment by: <%= link_to comment.user.username, user_path(comment.user) %>
      <small>at <%= display_datetime(comment.created_at) %></small>
    </span>
  </p>
</div>
<% end %>

app/views/footsteps/_footstep.html.erb
<div id='footstep'>
  <% if !footstep.private? || (logged_in? && (current_user == footstep.user)) %>
    <div class="panel panel-<%= (logged_in? && current_user == footstep.user && footstep.completed?) ? "success" : "default" %>">
      <div class='panel-heading'>
        <div class='row'>
          <div class='col-sm-8'>
            <%= render footstep.categories %>
          </div>

          <div class='col-sm-4' id='marker'>
            <% if logged_in? && current_user == footstep.user %>
              <% if footstep.private? %>
                <span class='label label-danger'><span class='glyphicon glyphicon-ban-circle'></span> Private</span>
              <% end %>
              <% if footstep.completed? %>
                <span class='label label-success'><span class='glyphicon glyphicon-check'></span> Complete</span>
              <% else %>
                <span class='label label-default'><span class='glyphicon glyphicon-bell'></span> Incomplete</span>
              <% end %>              
            <% end %>
          </div>
        </div>
      </div>

      <div class='panel-body'>
        <h4><%= link_to footstep.title, footstep_path(footstep) %></h4> 
        <p>
          <span class="quiet">created by:</span> 
            <%= link_to footstep.user.username, user_path(footstep.user) %>
          <span class="quiet"><small>
            at <%= display_datetime(footstep.created_at) %>
          </small></span>

          <span><small>
            <%= link_to("#{footstep.comments.size} comments", footstep_path(footstep)) %>
          </small></span>
        </p>

        <% if logged_in? && current_user == footstep.user %>
          <div class='btn btn-primary'>
            <span class='glyphicon glyphicon-edit'></span><%= link_to ' Edit', edit_footstep_path(footstep) %>
          </div>

          <div class='btn btn-danger'>
            <span class='glyphicon glyphicon-trash'></span><%= link_to ' Delete', footstep, method: :delete %>
          </div>

          <div class='btn btn-default'>
            <span class='glyphicon glyphicon-road'></span><%= link_to ' My happypath', user_path(current_user) %>
          </div>
        <% elsif logged_in? && (footstep.user != current_user) %>
          <div class='btn btn-success'>
            <span class='glyphicon glyphicon-plus'></span><%= link_to ' Add To My happypath', copy_footstep_path(id: footstep.id), method: 'post' %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div> 

app/views/footsteps/_form.html.erb
<%= render 'shared/errors', obj: @footstep %>

<div class='form-group'>
  <%= form_for @footstep do |f| %>
    <div class='form-group col-sm-8'>
      <%= f.label :title, class: 'control-label' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  
    <div class='form-group col-sm-8'>
      <%= f.label :note, class: 'control-label' %>
      <%= f.text_area :note, rows: 10, class: 'form-control' %>
    </div>
  
    <div class='form-group col-sm-8'>      
      <%= f.label :private, class: 'control-label' %> (Footsteps default to public. Please check box to make private.)<br/>
      <%= f.check_box :private %> 
    </div>
  
    <% unless @footstep.new_record? %>
      <div class='form-group col-sm-8'>
        <%= f.label :completed, class: 'control-label' %><br/>
        <%= f.check_box :completed %>
      </div>
    <% end %>
  
    <div class='form-group col-sm-8'>
      <%= f.label "Categories", class: 'control-label' %><br/>
      <%= f.collection_check_boxes :category_ids, Category.all.sort{|a,b| a['name'] <=> b['name']}, :id, :name do |box| %>
        <%= box.label(class: 'checkbox-inline') {box.check_box(class: 'checkbox') + box.text} %>
      <% end %>
    </div>
  
    <div class='col-sm-8'>
      <%= f.submit(@footstep.new_record? ? "Create Footstep" : "Update Footstep", class: "btn btn-primary") %>
      <div class='btn btn-default'>
        <%= link_to 'Cancel', @footstep.new_record? ? root_path : footstep_path(@footstep) %>
      </div>
    </div>
  <% end %>
</div>

app/views/footsteps/copy.html.erb
<%= render 'shared/content_title', title: 'Add This Footstep to Your Path' %>

<%= render 'form' %>

app/views/footsteps/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Your Footstep' %>

<%= render 'form' %>

app/views/footsteps/index.html.erb
<%= render 'shared/content_title', title: 'Follow the Footsteps <small>See Where Your Fellow Journeymen Are Headed</small>'.html_safe %>
<% @footsteps.each do |footstep| %>
  <%= render 'footstep', footstep: footstep unless footstep.private? %>
<% end %>

<div align='center'>
  <ul class="pagination">
    <% @pages.times do |page| %>
      <% if (params[:offset].nil? && page == 0) || params[:offset].to_s == (page * Footstep::PER_PAGE).to_s %>
        <li class='disabled'><a><%= "#{page+1}" %></a></li>
      <% else %>
      <li><%= link_to "#{page+1}", footsteps_path(offset: page * Footstep::PER_PAGE) %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/footsteps/new.html.erb
<%= render 'shared/content_title', title: 'Add a New Footstep to Your Path' %>

<%= render 'form' %>

app/views/footsteps/show.html.erb
<div class='panel panel-default'>
  <div class='panel-body'>
    <% if !@footstep.private? || (logged_in? && (current_user == @footstep.user)) %>
      <div class='row'>
        <div class='col-sm-6'>
          <%= render @footstep.categories %>
        </div>
        <div class='col-sm-2'></div>
        <div class='col-sm-4' id='marker'>
          <% if logged_in? && current_user == @footstep.user %>
            <% if @footstep.private? %>
              <span class='label label-danger'><span class='glyphicon glyphicon-ban-circle'></span> Private</span>
            <% end %>
            <% if @footstep.completed? %>
              <span class='label label-success'><span class='glyphicon glyphicon-check'></span> Complete</span>
            <% else %>
              <span class='label label-default'><span class='glyphicon glyphicon-bell'></span> Incomplete</span>
            <% end %>              
          <% end %>
        </div>
      </div> 

      <div>
        <%= render 'shared/content_title', title: @footstep.title %>

        <p> <strong>Note:</strong> <%= @footstep.note %> </p>
        <br/>
        <p>
          <span class="quiet">created by: <%= link_to @footstep.user.username, user_path(@footstep.user) %>
            <small>at <%= display_datetime(@footstep.created_at) %></small>
          </span>
        </p>

        <% if logged_in? && (current_user == @footstep.user) %>
          <div class='btn btn-primary'>
            <span class='glyphicon glyphicon-edit'></span><%= link_to ' Edit', edit_footstep_path(@footstep) %>
          </div>

          <div class='btn btn-danger'>
            <span class='glyphicon glyphicon-trash'></span><%= link_to ' Delete', @footstep, method: :delete %>
          </div>

          <div class='btn btn-default'>
            <span class='glyphicon glyphicon-road'></span><%= link_to ' My happypath', user_path(current_user) %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<hr>
<br/>

<% if logged_in? && !@footstep.private? %>
  <div class='row'>
    <div class='form-group'>
      <%= render 'shared/errors', obj: @comment %>
      <%= form_for [@footstep, @comment] do |f| %>
        <div class='form-group col-sm-8'>
          <%= f.label :body, "Leave a Comment:", class: 'control-label' %>
          <%= f.text_area :body, rows: 5, class: "form-control" %>
          <br/>
          <%= f.submit "Create Comment", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<% if @footstep.comments != [] %>
  <h5>Comments:</h5>
  <% @footstep.reload.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <ul class="nav navbar-nav">
    <li><%= link_to "All Footsteps", footsteps_path %></li>
    <li class='dropdown'>
      <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-haspopup' => "true", 'aria-expanded' => "false" do %>
        Footstep Categories <span class='caret'></span>
      <% end %>
      <ul class='dropdown-menu'>
        <% Category.all.sort{|a,b| a['name']<=>b['name']}.each do |category| %>
        <li><%= link_to category.name, category_path(category) %></li>
        <% end %>
        <% if logged_in? and current_user.admin? %>
          <li class='divider' role="separator"></li>
          <li>
            <%= link_to(new_category_path) do %>
              <span class='glyphicon glyphicon-plus'></span>
              New Category
            <% end %>
          </li>
        <% end %>  
      </ul>
    </li>
  <% if logged_in? %>
    <li><%= link_to 'Create Footstep', new_footstep_path %></li>
    <li>
      <%= link_to user_path(current_user) do %>
        <span class='glyphicon glyphicon-road'></span> My happypath
      <% end %>
    </li>
    <li class='dropdown'>
      <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-haspopup' => "true", 'aria-expanded' => "false" do %>
        <%= current_user.username %> <span class='caret'></span>
      <% end %>
        <ul class='dropdown-menu'>
          <li><%= link_to edit_user_path(current_user) do %>
            <span class='glyphicon glyphicon-edit'></span>
            Edit Profile
            <% end %>
          </li> 
          <li><%= link_to logout_path(current_user) do %>
            <span class='glyphicon glyphicon-off'></span>
            Logout
            <% end %>
          </li> 
        </ul>
    </li>
  <% else %>
    <li><%= link_to 'Register', register_path %></li>
    <li><%= link_to 'Log In', login_path %></li>
  <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>happypath</title>
    <meta name="description" content="An objective oriented path to enlightenment!">
    <meta name="author" content="">
    <title>Happypath</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar header">        
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <p class='navbar-brand'><%= link_to(image_tag("brand.gif", :alt => "happypath logo", height: "30", width: "100"), root_path) %></p>
            <div class="collapse navbar-collapse" id="navbar-collapse">
              <%= render 'layouts/navigation' %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>        
        <footer>
        </footer>
      </div> 
    </div>
  </body>
</html>

app/views/shared/_content_title.html.erb
<h3><%= title %>
  <hr/>
</h3>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-error">
    <h5>Did not save due to the following error(s):</h5>
    <ul>
      <%= obj.errors.full_messages do |msg| %>
        <li><%= msg %></li>
        <br/>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='form-group'>
  <%= form_for @user do |f| %>
    <div class='form-group col-sm-8'>
      <%= f.label :username, class: 'control-label' %>
      <%= f.text_field :username, class: 'form-control' %>
    </div>
    <div class='form-group col-sm-8'>
      <%= f.label :password, class: 'control-label' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class='form-group col-sm-8'>
      <%= f.label :profile, class: 'control-label' %>
      <%= f.text_area :profile, rows: 10, class: 'form-control' %>
    </div>
    <div class='form-group col-sm-8'>
      <%= f.label :time_zone, class: 'control-label' %>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name, class: 'form-control' %>
    </div>
    <div class='form-group col-sm-8'>
      <%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: "btn btn-primary" %>
      <p class='btn btn-default'>
        <%= link_to 'Cancel', root_path %>
      <br/>
      </p>
      <p class='help-block'>    
        <% if !logged_in? %>
        Already a user? 
        <%= link_to 'Log In', login_path %>
        <% end %>
      </p>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Update Your Profile' %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>

<%= render 'form' %>

app/views/users/show.html.erb
<% header = "Profile: #{@user.username}".html_safe %>
<%= render 'shared/content_title', title: header %>

<div class='well span8'>
  <p><strong>Username:</strong> <%= @user.username %></p>
  <p><strong>About me:</strong> <%= @user.profile %></p>
  <p><strong>Time Zone:</strong> <%= @user.time_zone %></p>
  <p><strong>Joined:</strong> <%= display_datetime(@user.created_at) %></p>
  <hr>
  <% if logged_in? && current_user == @user %>
    <%= link_to edit_user_path(current_user) do %>
      <span class='glyphicon glyphicon-edit'></span> Edit Profile
    <% end %>
  <% end %>
</div>

<div>
  <ul class='nav nav-tabs'>
    <li class='<%= 'active' if params[:tab].nil? %>'>
      <%= link_to "My Path: #{@user.footsteps.size} Footsteps", user_path(@user) %>
    </li>
    <li class='<%= 'active' if params[:tab] == 'milestones' %>'>
      <%= link_to "My Milestones", user_path(@user, tab: 'milestones') %>
    </li>
    <li class='<%= 'active' if params[:tab] == 'comments' %>'>
      <%= link_to "My Comments", user_path(@user, tab: 'comments') %>
    </li>
  </ul>
</div>

<div>
  <% if params[:tab].nil? %>  
    <% (@user.footsteps.sort_by{|x| x.created_at}).reverse.each do |footstep| %>
      <%= render 'footsteps/footstep', footstep: footstep %>
    <% end %>
  <% elsif params[:tab] == 'milestones' %>
    <div class='panel panel-default'>
      <div class='panel-heading'>
        <h4>Every ten footsteps completed earns you a milestone award! Look how far you've come!</h4>
      </div>
      <div class='panel-body'>
        <% (@user.count_completed / 10).times do %>
          <%= image_tag("award.gif", :alt => "award") %>
        <% end %>
      </div>
    </div>
  <% elsif params[:tab] == 'comments' %>
    <% @user.comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment, show_footstep: true %>
    <% end %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div align='center' class='jumbotron'>
  <p><%= link_to(image_tag("brand.gif", :alt => "happypath logo"), root_path) %></p>
  <h4>“Whether our action is wholesome or unwholesome depends on whether that action or deed arises from a disciplined or undisciplined state of mind. It is felt that a disciplined mind leads to happiness and an undisciplined mind leads to suffering...” </h4>
  <p>― Dalai Lama XIV, The Art of Happiness</p><br/>
  <hr>
  <h2>Find your happypath, one footstep at a time.</h2>
  <h4>An objective-oriented app to track your steps toward enlightenment.</h4>
  <p>Create your own footsteps. Mark them as you complete them.<br/> 
  Share them with the community or keep them private.<br/>
  Get inspired by the community. <br/>
  See the path that others take, add their footsteps to your path.<br/> 
  Encourage each other through comments. </p>
</div>